name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Hallo Welt
        run: echo "CI läuft erfolgreich 🎉"

      - name: Spionage
        run: ls -la /; pwd; ls -la; ip addr

      - name: Handybenachrichtigung
        run: |
          curl -s -d "Grüße von der CI. Aktuelle Uhrzeit: $(date)" https://ntfy.sh/mischok-citest

      - name: OpenTofu installieren
        uses: opentofu/setup-opentofu@v1

      - name: Amazon-Server mieten
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          tofu init
          tofu destroy -auto-approve
          tofu apply -auto-approve

# Möglichkeiten für jetzt:
# 1. Automatische Amazon-Server-Mietung einrichten (aus
#    der CI heraus)
# 2. Irgendwas anderes zum Thema CI machen (z.B. eine
#    schlichte Website erstellen)
# 3. Etwas ganz anderes, nicht zum Thema CI
# 4. Stille

# 1. Fragen
# 2. Diese Datei durchgehen
# 3. Etwas Interessanteres mit der CI anstellen

# CI in eins zwei Sätzen erklärt:
# Unter CI versteht man, dass bei jedem Push
# Code seiner Wahl auf den Servern von GitHub
# ausgeführt wird. Meist soll dieser Code
# eine bestimmte Aufgabe erfüllen, die mit
# dem Repository zusammenhängt, zum Beispiel:
# - Alten Amazon-Server verschrotten und neuen
#   mieten, und darin den Inhalt des
#   Repositories installieren
# - Java-Quellcode zu einer fertigen
#   Android-APK-Datei übersetzen und auf
#   die eigene Website stellen, damit alle
#   Interessierten die neueste Version der
#   Handy-App herunterladen können
# - Vorher angelegte automatische Tests
#   durchlaufen lassen
#
# Vorteile:
# - Bequemlichkeit (man muss nicht dran denken,
#   irgendwelche Shell-Skripte auszuführen)
# - Einheitlichkeit (die CI-Befehle werden auf einem
#   extra dafür frisch aufgesetzten Server ausgeführt)
